spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: com.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;NON_KEYWORDS=USER
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create-drop